/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import java.util.*;
import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AAlgorithmeProgramme extends PProgramme
{
    private PEntete _entete_;
    private TDebut _debut_;
    private final LinkedList<PInstructions> _instructions_ = new LinkedList<PInstructions>();
    private TFin _fin_;

    public AAlgorithmeProgramme()
    {
        // Constructor
    }

    public AAlgorithmeProgramme(
        @SuppressWarnings("hiding") PEntete _entete_,
        @SuppressWarnings("hiding") TDebut _debut_,
        @SuppressWarnings("hiding") List<?> _instructions_,
        @SuppressWarnings("hiding") TFin _fin_)
    {
        // Constructor
        setEntete(_entete_);

        setDebut(_debut_);

        setInstructions(_instructions_);

        setFin(_fin_);

    }

    @Override
    public Object clone()
    {
        return new AAlgorithmeProgramme(
            cloneNode(this._entete_),
            cloneNode(this._debut_),
            cloneList(this._instructions_),
            cloneNode(this._fin_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlgorithmeProgramme(this);
    }

    public PEntete getEntete()
    {
        return this._entete_;
    }

    public void setEntete(PEntete node)
    {
        if(this._entete_ != null)
        {
            this._entete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entete_ = node;
    }

    public TDebut getDebut()
    {
        return this._debut_;
    }

    public void setDebut(TDebut node)
    {
        if(this._debut_ != null)
        {
            this._debut_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._debut_ = node;
    }

    public LinkedList<PInstructions> getInstructions()
    {
        return this._instructions_;
    }

    public void setInstructions(List<?> list)
    {
        for(PInstructions e : this._instructions_)
        {
            e.parent(null);
        }
        this._instructions_.clear();

        for(Object obj_e : list)
        {
            PInstructions e = (PInstructions) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._instructions_.add(e);
        }
    }

    public TFin getFin()
    {
        return this._fin_;
    }

    public void setFin(TFin node)
    {
        if(this._fin_ != null)
        {
            this._fin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fin_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._entete_)
            + toString(this._debut_)
            + toString(this._instructions_)
            + toString(this._fin_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._entete_ == child)
        {
            this._entete_ = null;
            return;
        }

        if(this._debut_ == child)
        {
            this._debut_ = null;
            return;
        }

        if(this._instructions_.remove(child))
        {
            return;
        }

        if(this._fin_ == child)
        {
            this._fin_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._entete_ == oldChild)
        {
            setEntete((PEntete) newChild);
            return;
        }

        if(this._debut_ == oldChild)
        {
            setDebut((TDebut) newChild);
            return;
        }

        for(ListIterator<PInstructions> i = this._instructions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInstructions) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._fin_ == oldChild)
        {
            setFin((TFin) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
