/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AChaineMessageAdd extends PMessageAdd
{
    private TCaracteres _caracteres_;

    public AChaineMessageAdd()
    {
        // Constructor
    }

    public AChaineMessageAdd(
        @SuppressWarnings("hiding") TCaracteres _caracteres_)
    {
        // Constructor
        setCaracteres(_caracteres_);

    }

    @Override
    public Object clone()
    {
        return new AChaineMessageAdd(
            cloneNode(this._caracteres_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChaineMessageAdd(this);
    }

    public TCaracteres getCaracteres()
    {
        return this._caracteres_;
    }

    public void setCaracteres(TCaracteres node)
    {
        if(this._caracteres_ != null)
        {
            this._caracteres_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caracteres_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caracteres_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caracteres_ == child)
        {
            this._caracteres_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caracteres_ == oldChild)
        {
            setCaracteres((TCaracteres) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
