/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ACompleteStructureConditionnelle extends PStructureConditionnelle
{
    private PFormeComplete _formeComplete_;

    public ACompleteStructureConditionnelle()
    {
        // Constructor
    }

    public ACompleteStructureConditionnelle(
        @SuppressWarnings("hiding") PFormeComplete _formeComplete_)
    {
        // Constructor
        setFormeComplete(_formeComplete_);

    }

    @Override
    public Object clone()
    {
        return new ACompleteStructureConditionnelle(
            cloneNode(this._formeComplete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompleteStructureConditionnelle(this);
    }

    public PFormeComplete getFormeComplete()
    {
        return this._formeComplete_;
    }

    public void setFormeComplete(PFormeComplete node)
    {
        if(this._formeComplete_ != null)
        {
            this._formeComplete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formeComplete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formeComplete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formeComplete_ == child)
        {
            this._formeComplete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formeComplete_ == oldChild)
        {
            setFormeComplete((PFormeComplete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
