/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AConditionnelleInstructions extends PInstructions
{
    private PStructureConditionnelle _structureConditionnelle_;

    public AConditionnelleInstructions()
    {
        // Constructor
    }

    public AConditionnelleInstructions(
        @SuppressWarnings("hiding") PStructureConditionnelle _structureConditionnelle_)
    {
        // Constructor
        setStructureConditionnelle(_structureConditionnelle_);

    }

    @Override
    public Object clone()
    {
        return new AConditionnelleInstructions(
            cloneNode(this._structureConditionnelle_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionnelleInstructions(this);
    }

    public PStructureConditionnelle getStructureConditionnelle()
    {
        return this._structureConditionnelle_;
    }

    public void setStructureConditionnelle(PStructureConditionnelle node)
    {
        if(this._structureConditionnelle_ != null)
        {
            this._structureConditionnelle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._structureConditionnelle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._structureConditionnelle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._structureConditionnelle_ == child)
        {
            this._structureConditionnelle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._structureConditionnelle_ == oldChild)
        {
            setStructureConditionnelle((PStructureConditionnelle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
