/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AConditionCompose extends PConditionCompose
{
    private TParentheseO _parentheseO_;
    private PConditionCompose _conditionCompose_;
    private TParentheseF _parentheseF_;

    public AConditionCompose()
    {
        // Constructor
    }

    public AConditionCompose(
        @SuppressWarnings("hiding") TParentheseO _parentheseO_,
        @SuppressWarnings("hiding") PConditionCompose _conditionCompose_,
        @SuppressWarnings("hiding") TParentheseF _parentheseF_)
    {
        // Constructor
        setParentheseO(_parentheseO_);

        setConditionCompose(_conditionCompose_);

        setParentheseF(_parentheseF_);

    }

    @Override
    public Object clone()
    {
        return new AConditionCompose(
            cloneNode(this._parentheseO_),
            cloneNode(this._conditionCompose_),
            cloneNode(this._parentheseF_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionCompose(this);
    }

    public TParentheseO getParentheseO()
    {
        return this._parentheseO_;
    }

    public void setParentheseO(TParentheseO node)
    {
        if(this._parentheseO_ != null)
        {
            this._parentheseO_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseO_ = node;
    }

    public PConditionCompose getConditionCompose()
    {
        return this._conditionCompose_;
    }

    public void setConditionCompose(PConditionCompose node)
    {
        if(this._conditionCompose_ != null)
        {
            this._conditionCompose_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionCompose_ = node;
    }

    public TParentheseF getParentheseF()
    {
        return this._parentheseF_;
    }

    public void setParentheseF(TParentheseF node)
    {
        if(this._parentheseF_ != null)
        {
            this._parentheseF_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parentheseF_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parentheseO_)
            + toString(this._conditionCompose_)
            + toString(this._parentheseF_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parentheseO_ == child)
        {
            this._parentheseO_ = null;
            return;
        }

        if(this._conditionCompose_ == child)
        {
            this._conditionCompose_ = null;
            return;
        }

        if(this._parentheseF_ == child)
        {
            this._parentheseF_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parentheseO_ == oldChild)
        {
            setParentheseO((TParentheseO) newChild);
            return;
        }

        if(this._conditionCompose_ == oldChild)
        {
            setConditionCompose((PConditionCompose) newChild);
            return;
        }

        if(this._parentheseF_ == oldChild)
        {
            setParentheseF((TParentheseF) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
