/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ADefinitionEntete extends PEntete
{
    private TVariables _variables_;
    private PVariableDeclaration _variableDeclaration_;

    public ADefinitionEntete()
    {
        // Constructor
    }

    public ADefinitionEntete(
        @SuppressWarnings("hiding") TVariables _variables_,
        @SuppressWarnings("hiding") PVariableDeclaration _variableDeclaration_)
    {
        // Constructor
        setVariables(_variables_);

        setVariableDeclaration(_variableDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ADefinitionEntete(
            cloneNode(this._variables_),
            cloneNode(this._variableDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefinitionEntete(this);
    }

    public TVariables getVariables()
    {
        return this._variables_;
    }

    public void setVariables(TVariables node)
    {
        if(this._variables_ != null)
        {
            this._variables_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variables_ = node;
    }

    public PVariableDeclaration getVariableDeclaration()
    {
        return this._variableDeclaration_;
    }

    public void setVariableDeclaration(PVariableDeclaration node)
    {
        if(this._variableDeclaration_ != null)
        {
            this._variableDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variables_)
            + toString(this._variableDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variables_ == child)
        {
            this._variables_ = null;
            return;
        }

        if(this._variableDeclaration_ == child)
        {
            this._variableDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variables_ == oldChild)
        {
            setVariables((TVariables) newChild);
            return;
        }

        if(this._variableDeclaration_ == oldChild)
        {
            setVariableDeclaration((PVariableDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
