/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ADivisionFacteur extends PFacteur
{
    private PFacteur _facteur_;
    private TDiv _div_;
    private PTerme _terme_;

    public ADivisionFacteur()
    {
        // Constructor
    }

    public ADivisionFacteur(
        @SuppressWarnings("hiding") PFacteur _facteur_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PTerme _terme_)
    {
        // Constructor
        setFacteur(_facteur_);

        setDiv(_div_);

        setTerme(_terme_);

    }

    @Override
    public Object clone()
    {
        return new ADivisionFacteur(
            cloneNode(this._facteur_),
            cloneNode(this._div_),
            cloneNode(this._terme_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisionFacteur(this);
    }

    public PFacteur getFacteur()
    {
        return this._facteur_;
    }

    public void setFacteur(PFacteur node)
    {
        if(this._facteur_ != null)
        {
            this._facteur_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._facteur_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PTerme getTerme()
    {
        return this._terme_;
    }

    public void setTerme(PTerme node)
    {
        if(this._terme_ != null)
        {
            this._terme_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._terme_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._facteur_)
            + toString(this._div_)
            + toString(this._terme_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._facteur_ == child)
        {
            this._facteur_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._terme_ == child)
        {
            this._terme_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._facteur_ == oldChild)
        {
            setFacteur((PFacteur) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._terme_ == oldChild)
        {
            setTerme((PTerme) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
