/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AExpress extends PExpress
{
    private PFacteur _facteur_;

    public AExpress()
    {
        // Constructor
    }

    public AExpress(
        @SuppressWarnings("hiding") PFacteur _facteur_)
    {
        // Constructor
        setFacteur(_facteur_);

    }

    @Override
    public Object clone()
    {
        return new AExpress(
            cloneNode(this._facteur_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpress(this);
    }

    public PFacteur getFacteur()
    {
        return this._facteur_;
    }

    public void setFacteur(PFacteur node)
    {
        if(this._facteur_ != null)
        {
            this._facteur_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._facteur_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._facteur_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._facteur_ == child)
        {
            this._facteur_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._facteur_ == oldChild)
        {
            setFacteur((PFacteur) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
