/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AGlobaleStructureConditionnelle extends PStructureConditionnelle
{
    private PFormeGlobale _formeGlobale_;

    public AGlobaleStructureConditionnelle()
    {
        // Constructor
    }

    public AGlobaleStructureConditionnelle(
        @SuppressWarnings("hiding") PFormeGlobale _formeGlobale_)
    {
        // Constructor
        setFormeGlobale(_formeGlobale_);

    }

    @Override
    public Object clone()
    {
        return new AGlobaleStructureConditionnelle(
            cloneNode(this._formeGlobale_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGlobaleStructureConditionnelle(this);
    }

    public PFormeGlobale getFormeGlobale()
    {
        return this._formeGlobale_;
    }

    public void setFormeGlobale(PFormeGlobale node)
    {
        if(this._formeGlobale_ != null)
        {
            this._formeGlobale_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formeGlobale_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formeGlobale_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formeGlobale_ == child)
        {
            this._formeGlobale_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formeGlobale_ == oldChild)
        {
            setFormeGlobale((PFormeGlobale) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
