/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import java.util.*;
import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class APrefixeCompose extends PPrefixeCompose
{
    private final LinkedList<PPrefixe> _prefixe_ = new LinkedList<PPrefixe>();

    public APrefixeCompose()
    {
        // Constructor
    }

    public APrefixeCompose(
        @SuppressWarnings("hiding") List<?> _prefixe_)
    {
        // Constructor
        setPrefixe(_prefixe_);

    }

    @Override
    public Object clone()
    {
        return new APrefixeCompose(
            cloneList(this._prefixe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrefixeCompose(this);
    }

    public LinkedList<PPrefixe> getPrefixe()
    {
        return this._prefixe_;
    }

    public void setPrefixe(List<?> list)
    {
        for(PPrefixe e : this._prefixe_)
        {
            e.parent(null);
        }
        this._prefixe_.clear();

        for(Object obj_e : list)
        {
            PPrefixe e = (PPrefixe) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._prefixe_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prefixe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prefixe_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PPrefixe> i = this._prefixe_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPrefixe) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
