/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class APrefixe extends PPrefixe
{
    private TSeparateur _separateur_;
    private TIdentifiant _identifiant_;

    public APrefixe()
    {
        // Constructor
    }

    public APrefixe(
        @SuppressWarnings("hiding") TSeparateur _separateur_,
        @SuppressWarnings("hiding") TIdentifiant _identifiant_)
    {
        // Constructor
        setSeparateur(_separateur_);

        setIdentifiant(_identifiant_);

    }

    @Override
    public Object clone()
    {
        return new APrefixe(
            cloneNode(this._separateur_),
            cloneNode(this._identifiant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrefixe(this);
    }

    public TSeparateur getSeparateur()
    {
        return this._separateur_;
    }

    public void setSeparateur(TSeparateur node)
    {
        if(this._separateur_ != null)
        {
            this._separateur_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._separateur_ = node;
    }

    public TIdentifiant getIdentifiant()
    {
        return this._identifiant_;
    }

    public void setIdentifiant(TIdentifiant node)
    {
        if(this._identifiant_ != null)
        {
            this._identifiant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifiant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._separateur_)
            + toString(this._identifiant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._separateur_ == child)
        {
            this._separateur_ = null;
            return;
        }

        if(this._identifiant_ == child)
        {
            this._identifiant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._separateur_ == oldChild)
        {
            setSeparateur((TSeparateur) newChild);
            return;
        }

        if(this._identifiant_ == oldChild)
        {
            setIdentifiant((TIdentifiant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
