/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AReelType extends PType
{
    private TReel _reel_;

    public AReelType()
    {
        // Constructor
    }

    public AReelType(
        @SuppressWarnings("hiding") TReel _reel_)
    {
        // Constructor
        setReel(_reel_);

    }

    @Override
    public Object clone()
    {
        return new AReelType(
            cloneNode(this._reel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReelType(this);
    }

    public TReel getReel()
    {
        return this._reel_;
    }

    public void setReel(TReel node)
    {
        if(this._reel_ != null)
        {
            this._reel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._reel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._reel_ == child)
        {
            this._reel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._reel_ == oldChild)
        {
            setReel((TReel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
