/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleStructureConditionnelle extends PStructureConditionnelle
{
    private PFormeSimple _formeSimple_;

    public ASimpleStructureConditionnelle()
    {
        // Constructor
    }

    public ASimpleStructureConditionnelle(
        @SuppressWarnings("hiding") PFormeSimple _formeSimple_)
    {
        // Constructor
        setFormeSimple(_formeSimple_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleStructureConditionnelle(
            cloneNode(this._formeSimple_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleStructureConditionnelle(this);
    }

    public PFormeSimple getFormeSimple()
    {
        return this._formeSimple_;
    }

    public void setFormeSimple(PFormeSimple node)
    {
        if(this._formeSimple_ != null)
        {
            this._formeSimple_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formeSimple_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._formeSimple_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._formeSimple_ == child)
        {
            this._formeSimple_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._formeSimple_ == oldChild)
        {
            setFormeSimple((PFormeSimple) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
