/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ASingleVariableDeclaration extends PVariableDeclaration
{
    private TIdentifiant _identifiant_;
    private PSuffixe _suffixe_;

    public ASingleVariableDeclaration()
    {
        // Constructor
    }

    public ASingleVariableDeclaration(
        @SuppressWarnings("hiding") TIdentifiant _identifiant_,
        @SuppressWarnings("hiding") PSuffixe _suffixe_)
    {
        // Constructor
        setIdentifiant(_identifiant_);

        setSuffixe(_suffixe_);

    }

    @Override
    public Object clone()
    {
        return new ASingleVariableDeclaration(
            cloneNode(this._identifiant_),
            cloneNode(this._suffixe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleVariableDeclaration(this);
    }

    public TIdentifiant getIdentifiant()
    {
        return this._identifiant_;
    }

    public void setIdentifiant(TIdentifiant node)
    {
        if(this._identifiant_ != null)
        {
            this._identifiant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifiant_ = node;
    }

    public PSuffixe getSuffixe()
    {
        return this._suffixe_;
    }

    public void setSuffixe(PSuffixe node)
    {
        if(this._suffixe_ != null)
        {
            this._suffixe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._suffixe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifiant_)
            + toString(this._suffixe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifiant_ == child)
        {
            this._identifiant_ = null;
            return;
        }

        if(this._suffixe_ == child)
        {
            this._suffixe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifiant_ == oldChild)
        {
            setIdentifiant((TIdentifiant) newChild);
            return;
        }

        if(this._suffixe_ == oldChild)
        {
            setSuffixe((PSuffixe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
