/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ASoustractionExpress extends PExpress
{
    private PExpress _express_;
    private TMoins _moins_;
    private PFacteur _facteur_;

    public ASoustractionExpress()
    {
        // Constructor
    }

    public ASoustractionExpress(
        @SuppressWarnings("hiding") PExpress _express_,
        @SuppressWarnings("hiding") TMoins _moins_,
        @SuppressWarnings("hiding") PFacteur _facteur_)
    {
        // Constructor
        setExpress(_express_);

        setMoins(_moins_);

        setFacteur(_facteur_);

    }

    @Override
    public Object clone()
    {
        return new ASoustractionExpress(
            cloneNode(this._express_),
            cloneNode(this._moins_),
            cloneNode(this._facteur_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASoustractionExpress(this);
    }

    public PExpress getExpress()
    {
        return this._express_;
    }

    public void setExpress(PExpress node)
    {
        if(this._express_ != null)
        {
            this._express_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._express_ = node;
    }

    public TMoins getMoins()
    {
        return this._moins_;
    }

    public void setMoins(TMoins node)
    {
        if(this._moins_ != null)
        {
            this._moins_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moins_ = node;
    }

    public PFacteur getFacteur()
    {
        return this._facteur_;
    }

    public void setFacteur(PFacteur node)
    {
        if(this._facteur_ != null)
        {
            this._facteur_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._facteur_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._express_)
            + toString(this._moins_)
            + toString(this._facteur_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._express_ == child)
        {
            this._express_ = null;
            return;
        }

        if(this._moins_ == child)
        {
            this._moins_ = null;
            return;
        }

        if(this._facteur_ == child)
        {
            this._facteur_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._express_ == oldChild)
        {
            setExpress((PExpress) newChild);
            return;
        }

        if(this._moins_ == oldChild)
        {
            setMoins((TMoins) newChild);
            return;
        }

        if(this._facteur_ == oldChild)
        {
            setFacteur((PFacteur) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
