/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class ASupegalConditionSimple extends PConditionSimple
{
    private PTerme _gauche_;
    private TOperateurSuperieurEgal _operateurSuperieurEgal_;
    private PTerme _droite_;

    public ASupegalConditionSimple()
    {
        // Constructor
    }

    public ASupegalConditionSimple(
        @SuppressWarnings("hiding") PTerme _gauche_,
        @SuppressWarnings("hiding") TOperateurSuperieurEgal _operateurSuperieurEgal_,
        @SuppressWarnings("hiding") PTerme _droite_)
    {
        // Constructor
        setGauche(_gauche_);

        setOperateurSuperieurEgal(_operateurSuperieurEgal_);

        setDroite(_droite_);

    }

    @Override
    public Object clone()
    {
        return new ASupegalConditionSimple(
            cloneNode(this._gauche_),
            cloneNode(this._operateurSuperieurEgal_),
            cloneNode(this._droite_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASupegalConditionSimple(this);
    }

    public PTerme getGauche()
    {
        return this._gauche_;
    }

    public void setGauche(PTerme node)
    {
        if(this._gauche_ != null)
        {
            this._gauche_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gauche_ = node;
    }

    public TOperateurSuperieurEgal getOperateurSuperieurEgal()
    {
        return this._operateurSuperieurEgal_;
    }

    public void setOperateurSuperieurEgal(TOperateurSuperieurEgal node)
    {
        if(this._operateurSuperieurEgal_ != null)
        {
            this._operateurSuperieurEgal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operateurSuperieurEgal_ = node;
    }

    public PTerme getDroite()
    {
        return this._droite_;
    }

    public void setDroite(PTerme node)
    {
        if(this._droite_ != null)
        {
            this._droite_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._droite_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gauche_)
            + toString(this._operateurSuperieurEgal_)
            + toString(this._droite_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gauche_ == child)
        {
            this._gauche_ = null;
            return;
        }

        if(this._operateurSuperieurEgal_ == child)
        {
            this._operateurSuperieurEgal_ = null;
            return;
        }

        if(this._droite_ == child)
        {
            this._droite_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gauche_ == oldChild)
        {
            setGauche((PTerme) newChild);
            return;
        }

        if(this._operateurSuperieurEgal_ == oldChild)
        {
            setOperateurSuperieurEgal((TOperateurSuperieurEgal) newChild);
            return;
        }

        if(this._droite_ == oldChild)
        {
            setDroite((PTerme) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
