/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AValeurReelTerme extends PTerme
{
    private TNombreReel _nombreReel_;

    public AValeurReelTerme()
    {
        // Constructor
    }

    public AValeurReelTerme(
        @SuppressWarnings("hiding") TNombreReel _nombreReel_)
    {
        // Constructor
        setNombreReel(_nombreReel_);

    }

    @Override
    public Object clone()
    {
        return new AValeurReelTerme(
            cloneNode(this._nombreReel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValeurReelTerme(this);
    }

    public TNombreReel getNombreReel()
    {
        return this._nombreReel_;
    }

    public void setNombreReel(TNombreReel node)
    {
        if(this._nombreReel_ != null)
        {
            this._nombreReel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nombreReel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nombreReel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nombreReel_ == child)
        {
            this._nombreReel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nombreReel_ == oldChild)
        {
            setNombreReel((TNombreReel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
