/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AValeurTerme extends PTerme
{
    private TNumerique _numerique_;

    public AValeurTerme()
    {
        // Constructor
    }

    public AValeurTerme(
        @SuppressWarnings("hiding") TNumerique _numerique_)
    {
        // Constructor
        setNumerique(_numerique_);

    }

    @Override
    public Object clone()
    {
        return new AValeurTerme(
            cloneNode(this._numerique_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValeurTerme(this);
    }

    public TNumerique getNumerique()
    {
        return this._numerique_;
    }

    public void setNumerique(TNumerique node)
    {
        if(this._numerique_ != null)
        {
            this._numerique_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numerique_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numerique_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numerique_ == child)
        {
            this._numerique_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numerique_ == oldChild)
        {
            setNumerique((TNumerique) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
