/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AValeurEntiereTerme extends PTerme
{
    private TNombreEntier _nombreEntier_;

    public AValeurEntiereTerme()
    {
        // Constructor
    }

    public AValeurEntiereTerme(
        @SuppressWarnings("hiding") TNombreEntier _nombreEntier_)
    {
        // Constructor
        setNombreEntier(_nombreEntier_);

    }

    @Override
    public Object clone()
    {
        return new AValeurEntiereTerme(
            cloneNode(this._nombreEntier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValeurEntiereTerme(this);
    }

    public TNombreEntier getNombreEntier()
    {
        return this._nombreEntier_;
    }

    public void setNombreEntier(TNombreEntier node)
    {
        if(this._nombreEntier_ != null)
        {
            this._nombreEntier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nombreEntier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nombreEntier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nombreEntier_ == child)
        {
            this._nombreEntier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nombreEntier_ == oldChild)
        {
            setNombreEntier((TNombreEntier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
