/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class AVideEntete extends PEntete
{

    public AVideEntete()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVideEntete();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVideEntete(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
