/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TAlgorithme extends Token
{
    public TAlgorithme()
    {
        super.setText("algorithme");
    }

    public TAlgorithme(int line, int pos)
    {
        super.setText("algorithme");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAlgorithme(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAlgorithme(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAlgorithme text.");
    }
}
