/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TCaracteres extends Token
{
    public TCaracteres()
    {
        super.setText("\"tout_caractere\"");
    }

    public TCaracteres(int line, int pos)
    {
        super.setText("\"tout_caractere\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCaracteres(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCaracteres(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCaracteres text.");
    }
}
