/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TDef extends Token
{
    public TDef()
    {
        super.setText("en");
    }

    public TDef(int line, int pos)
    {
        super.setText("en");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDef(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDef(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDef text.");
    }
}
