/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TEcriture extends Token
{
    public TEcriture()
    {
        super.setText("ecrire");
    }

    public TEcriture(int line, int pos)
    {
        super.setText("ecrire");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEcriture(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEcriture(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEcriture text.");
    }
}
