/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TFin extends Token
{
    public TFin()
    {
        super.setText("fin");
    }

    public TFin(int line, int pos)
    {
        super.setText("fin");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFin(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFin(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFin text.");
    }
}
