/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TOperateurAffectation extends Token
{
    public TOperateurAffectation()
    {
        super.setText("<--");
    }

    public TOperateurAffectation(int line, int pos)
    {
        super.setText("<--");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperateurAffectation(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperateurAffectation(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperateurAffectation text.");
    }
}
