/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TOperateurModulo extends Token
{
    public TOperateurModulo()
    {
        super.setText("mod");
    }

    public TOperateurModulo(int line, int pos)
    {
        super.setText("mod");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOperateurModulo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOperateurModulo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOperateurModulo text.");
    }
}
