/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TPuissance extends Token
{
    public TPuissance()
    {
        super.setText("^");
    }

    public TPuissance(int line, int pos)
    {
        super.setText("^");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPuissance(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPuissance(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPuissance text.");
    }
}
