/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TReel extends Token
{
    public TReel()
    {
        super.setText("reel");
    }

    public TReel(int line, int pos)
    {
        super.setText("reel");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReel(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReel(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReel text.");
    }
}
