/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TSinon extends Token
{
    public TSinon()
    {
        super.setText("sinon");
    }

    public TSinon(int line, int pos)
    {
        super.setText("sinon");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSinon(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSinon(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSinon text.");
    }
}
