/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TSinonsi extends Token
{
    public TSinonsi()
    {
        super.setText("sinonsi");
    }

    public TSinonsi(int line, int pos)
    {
        super.setText("sinonsi");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSinonsi(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSinonsi(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSinonsi text.");
    }
}
