/* This file was generated by SableCC (http://www.sablecc.org/). */

package beatrice.node;

import beatrice.analysis.*;

@SuppressWarnings("nls")
public final class TVariable extends Token
{
    public TVariable()
    {
        super.setText("variable");
    }

    public TVariable(int line, int pos)
    {
        super.setText("variable");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVariable(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVariable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVariable text.");
    }
}
